- name: demo on play level varaibles
  hosts: frontend
  vars:
    COURSE: "ANSIBLE"
    TRAINER: "Praveen"
    DURATION: "130HRS"

  tasks: 
  - name: play level variables
    debug:
      msg: I am learning {{ COURSE }}, Trainer is {{ TRAINER }}, Duration is {{ DURATION }}
