- name: demo on file level varaibles
  hosts: frontend
  vars.files:
  - course.yaml
  tasks: 
  - name: file level variables
    debug:
      msg: I am learning {{ COURSE }}, Trainer is {{ TRAINER }}, Duration is {{ DURATION }}
