- name: demo on play level varaibles
  hosts: frontend
  vars.files:
  - course.yaml
  tasks: 
  - name: play level variables
    debug:
      msg: I am learning {{ COURSE }}, Trainer is {{ TRAINER }}, Duration is {{ DURATION }}
