- name: Demo on prompt level variables
  hosts: local
  connection: local
  vars_prompt:
  - name: username
    prompt: "Please enter username"
    private: true

  - name: password
    prompt: "pleae enter password"
    private: false

  tasks:
  - name: print username & password
    debug:
      msg: Username is {{ username }}, Password is {{ password }}